# Generated by Django 4.2.21 on 2025-10-04 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sets', to='expense_auth.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Set',
                'verbose_name_plural': 'User Sets',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='expense_auth.userset'),
        ),
    ]
