# Generated by Django 4.2.21 on 2025-10-04 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_auth', '0003_expense_receipt_expensecategory_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='current_stage',
            field=models.CharField(default='manager', help_text='Current approval stage', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='escalation_date',
            field=models.DateTimeField(blank=True, help_text='When to escalate if not approved', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sequence', models.JSONField(help_text='List of approval roles in sequence')),
                ('percentage_required', models.IntegerField(default=100, help_text='Percentage of approvers required')),
                ('admin_override', models.BooleanField(default=True)),
                ('urgent_bypass', models.BooleanField(default=True, help_text='Skip manager for urgent expenses')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='expense_auth.company')),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overridden', 'Overridden')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='expense_auth.expense')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='approval_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense_auth.approvalrule'),
        ),
    ]
